Repository signalwire/docs, pull requests merged in 2025-07, with the labels that each got.

#326 Document relay rest api endpoints
  api/signalwire-rest/space-api/_category_.yaml
  api/signalwire-rest/space-api/_spec_.yaml
Labels: area/rest-api

#335 [Conferences] 14718 - Add conferences endpoint list
  api/signalwire-rest/logs-api/conferences/main.tsp
  api/signalwire-rest/logs-api/conferences/models/core.tsp
  api/signalwire-rest/logs-api/conferences/models/responses.tsp
  api/signalwire-rest/logs-api/main.tsp
  api/signalwire-rest/logs-api/tsp-output/@typespec/openapi3/openapi.yaml
  config/pluginsConfig/docusaurus-plugin-openapi-docs.ts
  config/sidebarsConfig/rest-api-sidebar.ts
Labels: area/documentation

#356 Remove SWML Apps
  api/signalwire-rest/fabric-api/_spec_.yaml
  website/provisioning/nginx/redirects.map
Labels: area/rest-api

#385 Clean up OpenGraph titles and descriptions
  website/src/plugins/docusaurus-plugin-og/src/index.ts
Labels: area/general

#397 Hosted Messaging guide
  website/docs/main/home/messaging/sms/getting-started/sending-your-first-sms/index.mdx
  website/docs/main/home/messaging/sms/guides/hosted-messaging/index.mdx
  website/docs/main/home/platform/phone-numbers/getting-started/porting-into-signalwire.mdx
Labels: area/documentation

#425 Create new blog post to release @signalwire/js@3.29.1
  website/blog/releases/js/3.29.1/index.mdx
Labels: area/documentation
